# Site settings
title:       Brown Quantum Initiative
author:      Alan Bidart
baseurl:     ""
url:         "https://www.brownquantuminitiative.com"

header_pages:
  - index.md

keywords: ['Brown', 'Quantum', 'Quantum Computing', 'CS', 'computer science', 'talks', 'Brown University', 'Information Science', "Quantum Information", "Chemistry", "Physics", "Quantum Mechanics"]

# katex
katex:
  rendering_options:
    # Default KaTeX rendering options. See https://github.com/Khan/KaTeX#rendering-options
    throw_error: true                       # throwOnError - set to false if you want rendering to output error as text rather than a build error
    error_color: "#cc0000" 
    delimiters: [
              {left: "$$", right: "$$", display: true},
            {left: "$", right: "$", display: false}]

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data', 'strikethrough']
permalink:    pretty
sass:
  style: compressed
  sass_dir: ./_sass
plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-paginate
  - jekyll-katex
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - CNAME
  - node_modules


